### ISSUE TITLE
undefined method 'to_json'

### ISSUE THREAD

**Issue by rrapstine** [Shopify/shopify-cli#2227]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

app

### Expected behavior

`shopify foo` should do some action without error

### Actual behavior

Regardless of which command I try, whether its `shopify version` or `shopify login` or `shopify help`, I am met with an error:

```
undefined method `to_json' for {"TERM_SESSION_ID"=>"w0t0p0:7D83841E-3286-4C5C-8850-5BF0EE948AB7", "SSH_AUTH_SOCK"=>"/private/tmp/com.apple.launchd.LOK54WcLYO/Listeners", "LC_TERMINAL_VERSION"=>"3.4.15", "COLORFGBG"=>"15;0", "ITERM_PROFILE"=>"Default", "XPC_FLAGS"=>"0x0", "LANG"=>"en_US.UTF-8", "PWD"=>"/Users/richard/Desktop", "SHELL"=>"/bin/zsh", "__CFBundleIdentifier"=>"com.googlecode.iterm2", "SECURITYSESSIONID"=>"186b2", "TERM_PROGRAM_VERSION"=>"3.4.15", "TERM_PROGRAM"=>"iTerm.app", "PATH"=>"/opt/homebrew/lib/ruby/gems/3.1.0/bin:/opt/homebrew/opt/ruby/bin:node_modules/.bin:vendor/bin:/Users/richard/.node/bin:/Users/richard/.composer/vendor/bin:/Users/richard/.dotfiles/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin", "LC_TERMINAL"=>"iTerm2", "COLORTERM"=>"truecolor", "COMMAND_MODE"=>"unix2003", "TERM"=>"xterm-256color", "HOME"=>"/Users/richard", "TMPDIR"=>"/var/folders/ck/qln6chzs37b3w5fjrbl1xymm0000gn/T/", "USER"=>"richard", "XPC_SERVICE_NAME"=>"0", "LOGNAME"=>"richard", "LaunchInstanceID"=>"56BE09B9-0EC8-4C81-B8E2-F2272BCD3D22", "__CF_USER_TEXT_ENCODING"=>"0x1F5:0x0:0x0", "ITERM_SESSION_ID"=>"w0t0p0:7D83841E-3286-4C5C-8850-5BF0EE948AB7", "SHLVL"=>"1", "OLDPWD"=>"/Users/richard", "HOMEBREW_PREFIX"=>"/opt/homebrew", "HOMEBREW_CELLAR"=>"/opt/homebrew/Cellar", "HOMEBREW_REPOSITORY"=>"/opt/homebrew", "MANPATH"=>"/opt/homebrew/share/man::", "INFOPATH"=>"/opt/homebrew/share/info:", "DOTFILES"=>"/Users/richard/.dotfiles", "ZSH"=>"/Users/richard/.oh-my-zsh", "LC_ALL"=>"en_US.UTF-8", "EDITOR"=>"code", "PAGER"=>"less", "LESS"=>"-R", "LSCOLORS"=>"Gxfxcxdxbxegedabagacad", "_"=>"/opt/homebrew/bin/shopify"}:Hash (NoMethodError)
```

### Stack trace

```shell
Unable to perform a stack trace
```

### Reproduction steps

1. Install shopify-cli using Homebrew
2. Try `shopify version` to confirm everything works
3. Much sadness

### Operating System

Mac OS Monterey 12.2.1

### CLI version (run `shopify version` if you're not sure)

2.15.3

### Shell

iTerm2

### Ruby version (run `ruby -v` if you're not sure)

3.1.1p18

### What language and version are you using in your application?

Not applicable

**Comment by CostierLucas** [comment]
Same issue..

**Comment by denisenadal** [comment]
I'm experiencing this as well as on Mac OS Monterey 12.3 with ruby 2.6.8p205 and shopify-cli 2.15.3

**Comment by rbnhmll** [comment]
How would someone go about downgrading to the last stable version with Homebrew?

**Comment by tpage99** [comment]
Same issue as well...tried uninstalling and reinstalling and issue is persisting...

**Comment by StefanoDiLegami** [comment]
Same issue. Tried out a few things but found no way to install earlier versions with brew. Next time I better unlink the old versions instead of uninstalling it.

**Comment by ebba0194** [comment]
Same issue here. Upgraded OS to Monterey in case that was causing issues, no luck

**Comment by JasonHassold** [comment]
Pretty weird that Homebrew doesn't let you uninstall previous versions. 

I was able to figure out how to do so mostly following this guide https://remarkablemark.org/blog/2017/02/03/install-brew-package-version/, but below is the exact steps I took

1. Uninstall the current formula
```
brew uninstall shopify-cli
```
2. Confirm the tap path exists (should print single path with `shopify-cli.rb` at the end)
```
find $(brew --repository) -name shopify-cli.rb
```

## You can skip steps 3 - 6 if you want to revert to version 2.15.2 and just go to this address 
https://raw.githubusercontent.com/Shopify/homebrew-shopify/14a7dd42d07b25800b56304dbf401d42beabce2a/shopify-cli.rb

3. Get github address 
```
brew info shopify-cli
```
4. Go to URL -> Go to History

![image](https://user-images.githubusercontent.com/25469167/162337414-22d0b588-355d-4102-a288-6d778c3654cc.png)

5. Select the 2.15.2 version

![image](https://user-images.githubusercontent.com/25469167/162337555-c4b71af7-e4b1-40f2-9780-df8aac785158.png)

6. Select RAW

![image](https://user-images.githubusercontent.com/25469167/162337650-7545fd6f-ce6e-4a65-9869-bb1da4483440.png)

<img width="952" alt="image" src="https://user-images.githubusercontent.com/25469167/162338155-3f9fc81f-514e-4965-ace7-bc28217c0ae4.png">


7. Copy and paste this into your command line but don't run (it pastes whats in your clipboard to the shopify-cli.rb file)
```
pbpaste > $(find $(brew --repository) -name shopify-cli.rb)
```
8. Now copy the RAW text you navigated to in step 6 (or the url above)

9. Run the command from step 7

10. Install
```
brew install shopify-cli
```
11. Check shopify-cli version (should be 2.15.2 if using the link above)
```
shopify version
```

12. Reset shopify-cli.rb file
```
cd $(dirname $(find $(brew --repository) -name shopify-cli.rb | head -1)) && git checkout .
```
13. Pin current brew formula (prevent accidental upgrade)
```
brew pin shopify-cli
```

**Comment by 1deadpixl** [comment]
@JasonHassold Thanks for the clear steps to downgrade! Wasn't easy to find the right solution for getting Homebrew to install a specific version.

Here's a one-liner for version 2.15.2 using `curl` instead of copy/paste:
```bash
curl https://raw.githubusercontent.com/Shopify/homebrew-shopify/14a7dd42d07b25800b56304dbf401d42beabce2a/shopify-cli.rb > $(find $(brew --repository) -name shopify-cli.rb) && brew install shopify-cli
```
Make sure you `brew uninstall shopify-cli` first.

**Comment by JasonHassold** [comment]
@1deadpixl no problem, and nice improvement. Couldn't we just add the `brew uninstall shopify-cli` before the `curl ...` with an `&&`?

**Comment by spinsch** [comment]
i'm not familar with ruby but the following workaround works for me:

```bash
sudo vim /usr/local/Cellar/shopify-cli/2.15.3/bin/shopify
```
add `require 'json'` after `#!/usr/local/opt/ruby/bin/ruby --disable-gems`:
```ruby
#!/usr/local/opt/ruby/bin/ruby --disable-gems
require 'json'
ENV['ORIGINAL_ENV']=ENV.to_h.to_json
```
save with `:wq!`

specs
```
macOS Catalina 10.15.7
ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-darwin19]
Homebrew 3.4.5
Shopify-Cli 2.15.3
```

**Comment by petercampanelli** [comment]
Having same issue! Every shopify command including things as basic as `shopify version` are erroring. Urgently need this fixed!!

**Comment by hannachen** [comment]
👋 Thanks for reporting this issue and sharing your workarounds. We're attempting to resolve this right now, a potential fix went out to `2.15.4`. Could you please verify?

**Comment by chrisberthe** [comment]
Still present with `2.15.4`:
```bash
➜  ~ brew remove shopify-cli
Uninstalling /opt/homebrew/Cellar/shopify-cli/2.15.4... (2,161 files, 51.7MB)
➜  ~ brew install shopify-cli
==> Fetching shopify-cli from gem source
==> Installing shopify-cli from shopify/shopify
==> gem install /Users/chrisberthe/Library/Caches/Homebrew/shopify-cli-2.15.4.gem --no-document --no-wrapper --no-user-install --install-dir /opt/homebrew/Cellar/shopify-cli/2.15.4 --bindir /opt/homebrew/Cellar/sho
🍺  /opt/homebrew/Cellar/shopify-cli/2.15.4: 2,161 files, 51.7MB, built in 6 seconds
==> Running `brew cleanup shopify-cli`...
➜  ~ shopify version
/opt/homebrew/bin/shopify:2:in `<main>': undefined method `to_json' for { ... }:Hash (NoMethodError)
```

**Comment by hannachen** [comment]
Oops, the PR merge automatically closed the issue. Reopening until the release is out and verified.

**Comment by 1deadpixl** [comment]
The fix in 2.15.4 isn't working for me.
Here's what I did after downgrading to 2.15.2 yesterday:
```bash
❯ brew untap shopify/shopify
Untapping shopify/shopify...
Untapped 11 casks and 46 formulae (185 files, 754.4KB).

❯ brew tap shopify/shopify
==> Tapping shopify/shopify
...
Tapped 11 casks and 46 formulae (70 files, 661.4KB).

❯ brew install shopify-cli
==> Fetching shopify-cli from gem source
==> Installing shopify-cli from shopify/shopify
==> gem install /Users/philippe/Library/Caches/Homebrew/shopify-cli-2.15.4.gem --no-document --no-wrap
🍺  /usr/local/Cellar/shopify-cli/2.15.4: 2,161 files, 52MB, built in 25 seconds
==> Running `brew cleanup shopify-cli`...

❯ shopify version
/usr/local/bin/shopify:2:in `<main>': undefined method `to_json'...
```

Going back to 2.15.2 got everything chooching again...
```bash
❯ brew uninstall shopify-cli && curl https://raw.githubusercontent.com/Shopify/homebrew-shopify/14a7dd42d07b25800b56304dbf401d42beabce2a/shopify-cli.rb > $(find $(brew --repository) -name shopify-cli.rb) && brew install shopify-cli

❯ shopify version
2.15.2
```

**Comment by chrisberthe** [comment]
Back working with `2.15.5` 👍🏻

**Comment by hannachen** [comment]
Thanks for your patience everyone. This bug didn't come up during post-release verification due to the test environment using CLI installed via Ruby Gem rather than Homebrew. We're looking into additional integration tests/verification steps to avoid this situation in the future.

**Comment by 1deadpixl** [comment]
2.15.5 is working for me as well.
Thanks for the efforts!
