### ISSUE TITLE
[Bug]: NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by Sky-bits** [Shopify/shopify-cli#2727]
### Please confirm that you:

- [X] Are working with Shopify CLI 2.0, not 3.0. (You can [open a 3.0 issue here](https://github.com/Shopify/cli/issues/new/choose).)
- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

app

### Expected behavior

theme app extension shoud be register

### Actual behavior

it was not able to register

### Stack trace

```shell
/var/lib/gems/2.7.0/gems/shopify-cli-2.25.0/lib/project_types/extension/extension_project.rb:134:in `extra_property_present?'
/var/lib/gems/2.7.0/gems/shopify-cli-2.25.0/lib/project_types/extension/extension_project.rb:96:in `registration_id?'
/var/lib/gems/2.7.0/gems/shopify-cli-2.25.0/lib/project_types/extension/extension_project.rb:78:in `registered?'
/var/lib/gems/2.7.0/gems/shopify-cli-2.25.0/lib/project_types/extension/commands/register.rb:10:in `block in call'
/var/lib/gems/2.7.0/gems/shopify-cli-2.25.0/vendor/deps/cli-ui/lib/cli/ui/frame.rb:103:in `open'
```

### Reproduction steps

1. Create new app
2. create new theme app extension 
3.  do the extension register 'shopify extension register'
4.  i am getting the Error

### Operating System

x86_64-linux-gnu

### CLI version (run `shopify version` if you're not sure)

2.25.0

### Shell

/bin/bash

### Ruby version (run `ruby -v` if you're not sure)

2.7.0p0
